future: true
permalink: /:title/
url: http://mengfanhe.github.io
name: MifzllH
author: MifzllH
qq: 454787504
email: 454787504@qq.com

duoshuo: 
beian: 
cnzz: 
weibo: 
github: MengfanHe
about: "这里是 MifzllH 的个人博客，创建于 2017 年。"

safe: true
paginate: 20
